### ISSUE TITLE
Tab change colour

### ISSUE THREAD

**Issue by mariekeguy** [okfn/omeka-theme-glam#4]
The 'Browse items', 'Open Collections' and 'Lists of Collections' are all connected because all use http://omeka.okfn.org/items/browse at the start of the url.  For some reason the tab changing colour (to show you are on that tab) is acting a bit strange and not changing properly.

**Comment by smth** [comment]
Does this only happen with this theme? My initial thought is this is likely a core Omeka issue. In the short term I have disabled the highlighting all together (theme will need to be re-uploaded to see changes).

**Comment by smth** [comment]
Closing for now.
