### ISSUE TITLE
Form fields on contribute page difficult to see

### ISSUE THREAD

**Issue by mariekeguy** [okfn/omeka-theme-glam#6]
The form fields don't show on the http://omeka.okfn.org/contribution and http://omeka.okfn.org/items/search pages

**Comment by todrobbins** [comment]
See my pull request: https://github.com/okfn/omeka-theme-glam/pull/8

**Comment by smth** [comment]
This has already been fixed https://github.com/okfn/omeka-theme-glam/commit/96d7d9df705024752e4760e9d29814d5490d4ac4
